export type CanonicalErrorCode =
  | 'CONFIG_INVALID'
  | 'DATA_UNAVAILABLE'
  | 'UNSUPPORTED_MINT_OWNER'
  | 'RPC_TRANSIENT'
  | 'RPC_PERMANENT'
  | 'RETRY_EXHAUSTED'
  | 'RPC_URL_MISSING'
  | 'INVALID_POSITION'
  | 'ORCA_DECODE_FAILED'
  | 'NOT_SOL_USDC'
  | 'ALREADY_EXECUTED_THIS_EPOCH'
  | 'LOCAL_RECEIPT_PENDING'
  | 'RECEIPT_PROGRAM_NOT_CONFIGURED'
  | 'RECEIPT_IDL_MISMATCH'
  | 'RECEIPT_PROGRAM_VERIFICATION_FAILED'
  | 'QUOTE_STALE'
  | 'SIMULATION_FAILED'
  | 'SLIPPAGE_EXCEEDED'
  | 'INSUFFICIENT_FEE_BUFFER'
  | 'BLOCKHASH_EXPIRED'
  | 'MISSING_ATTESTATION_HASH'
  | 'SWAP_ROUTER_UNSUPPORTED_CLUSTER'
  | 'UNSUPPORTED_SWAP_ROUTE'
  | 'POSTCONDITION_FAILED'
  | 'EXECUTION_PAUSED'
  | 'EXECUTION_MODE_BLOCKED'
  | 'EXECUTION_MODE_SEND_FORBIDDEN'
  | 'WALLET_PROVIDER_MISSING'
  | 'RUNTIME_MODE_INVALID'
  | 'RECEIPT_CONFIG_INCOMPLETE_FOR_SHADOW';

export type ShadowSimulationClass =
  | 'SIM_OK'
  | 'SIM_RPC_ERROR'
  | 'SIM_ACCOUNT_MISSING'
  | 'SIM_QUOTE_STALE'
  | 'SIM_SLIPPAGE_EXCEEDED'
  | 'SIM_TOKEN2022_ACCOUNT_MISMATCH'
  | 'SIM_RECEIPT_CONFIG_ERROR'
  | 'SIM_UNKNOWN';

export type SolanaConfig = {
  rpcUrl: string;
  cluster: 'devnet' | 'mainnet' | 'localnet';
  commitment: 'processed' | 'confirmed' | 'finalized';
};

export type NormalizedError = {
  code: CanonicalErrorCode;
  message: string;
  retryable: boolean;
  debug?: unknown;
};
